// Code generated by protoc-gen-go. DO NOT EDIT.
// source: board.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BoardDetailsReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Fqbn                 string    `protobuf:"bytes,2,opt,name=fqbn,proto3" json:"fqbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardDetailsReq) Reset()         { *m = BoardDetailsReq{} }
func (m *BoardDetailsReq) String() string { return proto.CompactTextString(m) }
func (*BoardDetailsReq) ProtoMessage()    {}
func (*BoardDetailsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937f74b042f92c0f, []int{0}
}

func (m *BoardDetailsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardDetailsReq.Unmarshal(m, b)
}
func (m *BoardDetailsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardDetailsReq.Marshal(b, m, deterministic)
}
func (m *BoardDetailsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardDetailsReq.Merge(m, src)
}
func (m *BoardDetailsReq) XXX_Size() int {
	return xxx_messageInfo_BoardDetailsReq.Size(m)
}
func (m *BoardDetailsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardDetailsReq.DiscardUnknown(m)
}

var xxx_messageInfo_BoardDetailsReq proto.InternalMessageInfo

func (m *BoardDetailsReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *BoardDetailsReq) GetFqbn() string {
	if m != nil {
		return m.Fqbn
	}
	return ""
}

type BoardDetailsResp struct {
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConfigOptions        []*ConfigOption `protobuf:"bytes,3,rep,name=config_options,json=configOptions,proto3" json:"config_options,omitempty"`
	RequiredTools        []*RequiredTool `protobuf:"bytes,4,rep,name=required_tools,json=requiredTools,proto3" json:"required_tools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BoardDetailsResp) Reset()         { *m = BoardDetailsResp{} }
func (m *BoardDetailsResp) String() string { return proto.CompactTextString(m) }
func (*BoardDetailsResp) ProtoMessage()    {}
func (*BoardDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_937f74b042f92c0f, []int{1}
}

func (m *BoardDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardDetailsResp.Unmarshal(m, b)
}
func (m *BoardDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardDetailsResp.Marshal(b, m, deterministic)
}
func (m *BoardDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardDetailsResp.Merge(m, src)
}
func (m *BoardDetailsResp) XXX_Size() int {
	return xxx_messageInfo_BoardDetailsResp.Size(m)
}
func (m *BoardDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_BoardDetailsResp proto.InternalMessageInfo

func (m *BoardDetailsResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoardDetailsResp) GetConfigOptions() []*ConfigOption {
	if m != nil {
		return m.ConfigOptions
	}
	return nil
}

func (m *BoardDetailsResp) GetRequiredTools() []*RequiredTool {
	if m != nil {
		return m.RequiredTools
	}
	return nil
}

type ConfigOption struct {
	Option               string         `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	OptionLabel          string         `protobuf:"bytes,2,opt,name=option_label,json=optionLabel,proto3" json:"option_label,omitempty"`
	Values               []*ConfigValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigOption) Reset()         { *m = ConfigOption{} }
func (m *ConfigOption) String() string { return proto.CompactTextString(m) }
func (*ConfigOption) ProtoMessage()    {}
func (*ConfigOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_937f74b042f92c0f, []int{2}
}

func (m *ConfigOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigOption.Unmarshal(m, b)
}
func (m *ConfigOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigOption.Marshal(b, m, deterministic)
}
func (m *ConfigOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigOption.Merge(m, src)
}
func (m *ConfigOption) XXX_Size() int {
	return xxx_messageInfo_ConfigOption.Size(m)
}
func (m *ConfigOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigOption.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigOption proto.InternalMessageInfo

func (m *ConfigOption) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *ConfigOption) GetOptionLabel() string {
	if m != nil {
		return m.OptionLabel
	}
	return ""
}

func (m *ConfigOption) GetValues() []*ConfigValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type ConfigValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ValueLabel           string   `protobuf:"bytes,2,opt,name=value_label,json=valueLabel,proto3" json:"value_label,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigValue) Reset()         { *m = ConfigValue{} }
func (m *ConfigValue) String() string { return proto.CompactTextString(m) }
func (*ConfigValue) ProtoMessage()    {}
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_937f74b042f92c0f, []int{3}
}

func (m *ConfigValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigValue.Unmarshal(m, b)
}
func (m *ConfigValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigValue.Marshal(b, m, deterministic)
}
func (m *ConfigValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigValue.Merge(m, src)
}
func (m *ConfigValue) XXX_Size() int {
	return xxx_messageInfo_ConfigValue.Size(m)
}
func (m *ConfigValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigValue proto.InternalMessageInfo

func (m *ConfigValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigValue) GetValueLabel() string {
	if m != nil {
		return m.ValueLabel
	}
	return ""
}

func (m *ConfigValue) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type RequiredTool struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Packager             string   `protobuf:"bytes,3,opt,name=packager,proto3" json:"packager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequiredTool) Reset()         { *m = RequiredTool{} }
func (m *RequiredTool) String() string { return proto.CompactTextString(m) }
func (*RequiredTool) ProtoMessage()    {}
func (*RequiredTool) Descriptor() ([]byte, []int) {
	return fileDescriptor_937f74b042f92c0f, []int{4}
}

func (m *RequiredTool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequiredTool.Unmarshal(m, b)
}
func (m *RequiredTool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequiredTool.Marshal(b, m, deterministic)
}
func (m *RequiredTool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequiredTool.Merge(m, src)
}
func (m *RequiredTool) XXX_Size() int {
	return xxx_messageInfo_RequiredTool.Size(m)
}
func (m *RequiredTool) XXX_DiscardUnknown() {
	xxx_messageInfo_RequiredTool.DiscardUnknown(m)
}

var xxx_messageInfo_RequiredTool proto.InternalMessageInfo

func (m *RequiredTool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequiredTool) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RequiredTool) GetPackager() string {
	if m != nil {
		return m.Packager
	}
	return ""
}

func init() {
	proto.RegisterType((*BoardDetailsReq)(nil), "arduino.BoardDetailsReq")
	proto.RegisterType((*BoardDetailsResp)(nil), "arduino.BoardDetailsResp")
	proto.RegisterType((*ConfigOption)(nil), "arduino.ConfigOption")
	proto.RegisterType((*ConfigValue)(nil), "arduino.ConfigValue")
	proto.RegisterType((*RequiredTool)(nil), "arduino.RequiredTool")
}

func init() { proto.RegisterFile("board.proto", fileDescriptor_937f74b042f92c0f) }

var fileDescriptor_937f74b042f92c0f = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcd, 0x0b, 0xd3, 0x30,
	0x14, 0xa7, 0x6e, 0xee, 0xe3, 0xb5, 0xf3, 0x23, 0x4c, 0x29, 0xbb, 0x58, 0x8b, 0x87, 0x1e, 0x5c,
	0x07, 0xf3, 0xea, 0x69, 0x7a, 0x11, 0x04, 0x21, 0x0c, 0x11, 0x2f, 0x33, 0x4d, 0xb3, 0x19, 0x4c,
	0x93, 0x2e, 0x69, 0xe7, 0xff, 0xe3, 0x5f, 0x2a, 0x49, 0xd3, 0xd2, 0xed, 0xd4, 0xf7, 0xfb, 0x78,
	0xbf, 0xf7, 0x5e, 0x28, 0x84, 0x85, 0x22, 0xba, 0xcc, 0x6b, 0xad, 0x1a, 0x85, 0xe6, 0x44, 0x97,
	0x2d, 0x97, 0x6a, 0x13, 0x51, 0x55, 0x55, 0x4a, 0x76, 0x74, 0x7a, 0x84, 0xe7, 0x07, 0xeb, 0xfa,
	0xcc, 0x1a, 0xc2, 0x85, 0xc1, 0xec, 0x8a, 0xb6, 0xb0, 0xe0, 0xd2, 0x34, 0x44, 0x52, 0x16, 0x07,
	0x49, 0x90, 0x85, 0xfb, 0x97, 0xb9, 0x6f, 0xce, 0xbf, 0x78, 0x01, 0x0f, 0x16, 0x84, 0x60, 0x7a,
	0xbe, 0x16, 0x32, 0x7e, 0x92, 0x04, 0xd9, 0x12, 0xbb, 0x3a, 0xfd, 0x17, 0xc0, 0x8b, 0xfb, 0x58,
	0x53, 0x5b, 0xa3, 0x24, 0x15, 0xeb, 0x8d, 0xb6, 0x46, 0x1f, 0xe1, 0x19, 0x55, 0xf2, 0xcc, 0x2f,
	0x27, 0x55, 0x37, 0x5c, 0x49, 0x13, 0x4f, 0x92, 0x49, 0x16, 0xee, 0x5f, 0x0d, 0x13, 0x3f, 0x39,
	0xf9, 0x9b, 0x53, 0xf1, 0x8a, 0x8e, 0x90, 0xb1, 0xdd, 0x9a, 0x5d, 0x5b, 0xae, 0x59, 0x79, 0x6a,
	0x94, 0x12, 0x26, 0x9e, 0x3e, 0x74, 0x63, 0x2f, 0x1f, 0x95, 0x12, 0x78, 0xa5, 0x47, 0xc8, 0xa4,
	0x7f, 0x21, 0x1a, 0x87, 0xa3, 0xd7, 0x30, 0xeb, 0x96, 0x70, 0x57, 0x2f, 0xb1, 0x47, 0xe8, 0x2d,
	0x44, 0x5d, 0x75, 0x12, 0xa4, 0x60, 0xc2, 0xef, 0x1f, 0x76, 0xdc, 0x57, 0x4b, 0xa1, 0xf7, 0x30,
	0xbb, 0x11, 0xd1, 0xb2, 0x7e, 0xfd, 0xf5, 0xc3, 0xfa, 0xdf, 0xad, 0x88, 0xbd, 0x27, 0xfd, 0x05,
	0xe1, 0x88, 0x46, 0x6b, 0x78, 0xea, 0x04, 0x3f, 0xb6, 0x03, 0xe8, 0x0d, 0x84, 0xae, 0xb8, 0x1b,
	0x0a, 0x8e, 0xea, 0x66, 0x6e, 0x60, 0x61, 0x98, 0x60, 0xb4, 0x61, 0x65, 0x3c, 0x49, 0x82, 0x6c,
	0x81, 0x07, 0x9c, 0xfe, 0x80, 0x68, 0x7c, 0xf9, 0xf0, 0xf4, 0xc1, 0xe8, 0xe9, 0x63, 0x98, 0xdf,
	0x98, 0x36, 0xf6, 0xde, 0x2e, 0xbc, 0x87, 0x36, 0xb9, 0x26, 0xf4, 0x0f, 0xb9, 0x30, 0xed, 0x92,
	0x97, 0x78, 0xc0, 0x87, 0x77, 0x3f, 0xd3, 0x0b, 0x6f, 0x7e, 0xb7, 0x45, 0x4e, 0x55, 0xb5, 0xf3,
	0x57, 0xf6, 0xdf, 0x2d, 0x15, 0x7c, 0xa7, 0x6b, 0x5a, 0xcc, 0xdc, 0xcf, 0xf5, 0xe1, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x83, 0x5b, 0xed, 0xbd, 0x82, 0x02, 0x00, 0x00,
}
