// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DownloadProgress struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	TotalSize            int64    `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Downloaded           int64    `protobuf:"varint,4,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Completed            bool     `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadProgress) Reset()         { *m = DownloadProgress{} }
func (m *DownloadProgress) String() string { return proto.CompactTextString(m) }
func (*DownloadProgress) ProtoMessage()    {}
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *DownloadProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadProgress.Unmarshal(m, b)
}
func (m *DownloadProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadProgress.Marshal(b, m, deterministic)
}
func (m *DownloadProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadProgress.Merge(m, src)
}
func (m *DownloadProgress) XXX_Size() int {
	return xxx_messageInfo_DownloadProgress.Size(m)
}
func (m *DownloadProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadProgress.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadProgress proto.InternalMessageInfo

func (m *DownloadProgress) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadProgress) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *DownloadProgress) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *DownloadProgress) GetDownloaded() int64 {
	if m != nil {
		return m.Downloaded
	}
	return 0
}

func (m *DownloadProgress) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type TaskProgress struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskProgress) Reset()         { *m = TaskProgress{} }
func (m *TaskProgress) String() string { return proto.CompactTextString(m) }
func (*TaskProgress) ProtoMessage()    {}
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *TaskProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProgress.Unmarshal(m, b)
}
func (m *TaskProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProgress.Marshal(b, m, deterministic)
}
func (m *TaskProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProgress.Merge(m, src)
}
func (m *TaskProgress) XXX_Size() int {
	return xxx_messageInfo_TaskProgress.Size(m)
}
func (m *TaskProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProgress.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProgress proto.InternalMessageInfo

func (m *TaskProgress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskProgress) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskProgress) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*Instance)(nil), "arduino.Instance")
	proto.RegisterType((*DownloadProgress)(nil), "arduino.DownloadProgress")
	proto.RegisterType((*TaskProgress)(nil), "arduino.TaskProgress")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xe9, 0x9f, 0x75, 0xb7, 0xc3, 0x22, 0x4b, 0x4e, 0x41, 0x54, 0x4a, 0xf1, 0xd0, 0x8b,
	0xbb, 0x07, 0xbf, 0x81, 0x78, 0xf1, 0x26, 0xd5, 0xd3, 0x5e, 0x24, 0x9b, 0x8c, 0x35, 0x98, 0x64,
	0x4a, 0x92, 0x22, 0xec, 0xf7, 0xf0, 0xfb, 0x8a, 0xa1, 0xf5, 0xdf, 0x69, 0xde, 0xfc, 0x66, 0x78,
	0x3c, 0x1e, 0xac, 0x25, 0x59, 0x4b, 0x6e, 0x3b, 0x78, 0x8a, 0xc4, 0x96, 0xc2, 0xab, 0x51, 0x3b,
	0x6a, 0xce, 0x60, 0x75, 0xef, 0x42, 0x14, 0x4e, 0x22, 0x3b, 0x85, 0x5c, 0x2b, 0x9e, 0xd5, 0x59,
	0xbb, 0xe8, 0x72, 0xad, 0x9a, 0x8f, 0x0c, 0x36, 0x77, 0xf4, 0xee, 0x0c, 0x09, 0xf5, 0xe0, 0xa9,
	0xf7, 0x18, 0x02, 0xdb, 0x40, 0x31, 0x7a, 0x93, 0xbe, 0xaa, 0xee, 0x4b, 0x32, 0x06, 0xe5, 0x8b,
	0x36, 0xc8, 0xf3, 0x84, 0x92, 0x66, 0x17, 0x00, 0x91, 0xa2, 0x30, 0xcf, 0x41, 0x1f, 0x91, 0x17,
	0x75, 0xd6, 0x16, 0x5d, 0x95, 0xc8, 0xa3, 0x3e, 0x22, 0xbb, 0x04, 0x50, 0x93, 0x31, 0x2a, 0x5e,
	0xa6, 0xf3, 0x2f, 0xc2, 0xce, 0xa1, 0x92, 0x64, 0x07, 0x83, 0x11, 0x15, 0x5f, 0xd4, 0x59, 0xbb,
	0xea, 0x7e, 0x40, 0xb3, 0x87, 0xf5, 0x93, 0x08, 0x6f, 0xdf, 0x91, 0x18, 0x94, 0x4e, 0x58, 0x9c,
	0x32, 0x25, 0xcd, 0x38, 0x2c, 0x2d, 0x86, 0x20, 0xfa, 0x39, 0xd7, 0xbc, 0xfe, 0xf5, 0x2e, 0xfe,
	0x79, 0xdf, 0x5e, 0xed, 0x9b, 0x5e, 0xc7, 0xd7, 0xf1, 0xb0, 0x95, 0x64, 0x77, 0x53, 0x4b, 0xf3,
	0xbc, 0x96, 0x46, 0xef, 0xfc, 0x20, 0x0f, 0x27, 0xa9, 0xc5, 0x9b, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x77, 0xb1, 0xae, 0x55, 0x01, 0x00, 0x00,
}
