// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlatformInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformInstallReq) Reset()         { *m = PlatformInstallReq{} }
func (m *PlatformInstallReq) String() string { return proto.CompactTextString(m) }
func (*PlatformInstallReq) ProtoMessage()    {}
func (*PlatformInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *PlatformInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInstallReq.Unmarshal(m, b)
}
func (m *PlatformInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInstallReq.Marshal(b, m, deterministic)
}
func (m *PlatformInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInstallReq.Merge(m, src)
}
func (m *PlatformInstallReq) XXX_Size() int {
	return xxx_messageInfo_PlatformInstallReq.Size(m)
}
func (m *PlatformInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInstallReq proto.InternalMessageInfo

func (m *PlatformInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformInstallReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformInstallReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformInstallResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformInstallResp) Reset()         { *m = PlatformInstallResp{} }
func (m *PlatformInstallResp) String() string { return proto.CompactTextString(m) }
func (*PlatformInstallResp) ProtoMessage()    {}
func (*PlatformInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *PlatformInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInstallResp.Unmarshal(m, b)
}
func (m *PlatformInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInstallResp.Marshal(b, m, deterministic)
}
func (m *PlatformInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInstallResp.Merge(m, src)
}
func (m *PlatformInstallResp) XXX_Size() int {
	return xxx_messageInfo_PlatformInstallResp.Size(m)
}
func (m *PlatformInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInstallResp proto.InternalMessageInfo

func (m *PlatformInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *PlatformInstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type PlatformDownloadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformDownloadReq) Reset()         { *m = PlatformDownloadReq{} }
func (m *PlatformDownloadReq) String() string { return proto.CompactTextString(m) }
func (*PlatformDownloadReq) ProtoMessage()    {}
func (*PlatformDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *PlatformDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformDownloadReq.Unmarshal(m, b)
}
func (m *PlatformDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformDownloadReq.Marshal(b, m, deterministic)
}
func (m *PlatformDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformDownloadReq.Merge(m, src)
}
func (m *PlatformDownloadReq) XXX_Size() int {
	return xxx_messageInfo_PlatformDownloadReq.Size(m)
}
func (m *PlatformDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformDownloadReq proto.InternalMessageInfo

func (m *PlatformDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformDownloadReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformDownloadReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformDownloadResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformDownloadResp) Reset()         { *m = PlatformDownloadResp{} }
func (m *PlatformDownloadResp) String() string { return proto.CompactTextString(m) }
func (*PlatformDownloadResp) ProtoMessage()    {}
func (*PlatformDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *PlatformDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformDownloadResp.Unmarshal(m, b)
}
func (m *PlatformDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformDownloadResp.Marshal(b, m, deterministic)
}
func (m *PlatformDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformDownloadResp.Merge(m, src)
}
func (m *PlatformDownloadResp) XXX_Size() int {
	return xxx_messageInfo_PlatformDownloadResp.Size(m)
}
func (m *PlatformDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformDownloadResp proto.InternalMessageInfo

func (m *PlatformDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type PlatformUninstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformUninstallReq) Reset()         { *m = PlatformUninstallReq{} }
func (m *PlatformUninstallReq) String() string { return proto.CompactTextString(m) }
func (*PlatformUninstallReq) ProtoMessage()    {}
func (*PlatformUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{4}
}

func (m *PlatformUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUninstallReq.Unmarshal(m, b)
}
func (m *PlatformUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUninstallReq.Marshal(b, m, deterministic)
}
func (m *PlatformUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUninstallReq.Merge(m, src)
}
func (m *PlatformUninstallReq) XXX_Size() int {
	return xxx_messageInfo_PlatformUninstallReq.Size(m)
}
func (m *PlatformUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUninstallReq proto.InternalMessageInfo

func (m *PlatformUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformUninstallReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformUninstallReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *PlatformUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlatformUninstallResp struct {
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlatformUninstallResp) Reset()         { *m = PlatformUninstallResp{} }
func (m *PlatformUninstallResp) String() string { return proto.CompactTextString(m) }
func (*PlatformUninstallResp) ProtoMessage()    {}
func (*PlatformUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{5}
}

func (m *PlatformUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUninstallResp.Unmarshal(m, b)
}
func (m *PlatformUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUninstallResp.Marshal(b, m, deterministic)
}
func (m *PlatformUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUninstallResp.Merge(m, src)
}
func (m *PlatformUninstallResp) XXX_Size() int {
	return xxx_messageInfo_PlatformUninstallResp.Size(m)
}
func (m *PlatformUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUninstallResp proto.InternalMessageInfo

func (m *PlatformUninstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type PlatformUpgradeReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	PlatformPackage      string    `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage,proto3" json:"platform_package,omitempty"`
	Architecture         string    `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformUpgradeReq) Reset()         { *m = PlatformUpgradeReq{} }
func (m *PlatformUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*PlatformUpgradeReq) ProtoMessage()    {}
func (*PlatformUpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{6}
}

func (m *PlatformUpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUpgradeReq.Unmarshal(m, b)
}
func (m *PlatformUpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUpgradeReq.Marshal(b, m, deterministic)
}
func (m *PlatformUpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUpgradeReq.Merge(m, src)
}
func (m *PlatformUpgradeReq) XXX_Size() int {
	return xxx_messageInfo_PlatformUpgradeReq.Size(m)
}
func (m *PlatformUpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUpgradeReq proto.InternalMessageInfo

func (m *PlatformUpgradeReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformUpgradeReq) GetPlatformPackage() string {
	if m != nil {
		return m.PlatformPackage
	}
	return ""
}

func (m *PlatformUpgradeReq) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

type PlatformUpgradeResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlatformUpgradeResp) Reset()         { *m = PlatformUpgradeResp{} }
func (m *PlatformUpgradeResp) String() string { return proto.CompactTextString(m) }
func (*PlatformUpgradeResp) ProtoMessage()    {}
func (*PlatformUpgradeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{7}
}

func (m *PlatformUpgradeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformUpgradeResp.Unmarshal(m, b)
}
func (m *PlatformUpgradeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformUpgradeResp.Marshal(b, m, deterministic)
}
func (m *PlatformUpgradeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformUpgradeResp.Merge(m, src)
}
func (m *PlatformUpgradeResp) XXX_Size() int {
	return xxx_messageInfo_PlatformUpgradeResp.Size(m)
}
func (m *PlatformUpgradeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformUpgradeResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformUpgradeResp proto.InternalMessageInfo

func (m *PlatformUpgradeResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *PlatformUpgradeResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type PlatformSearchReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SearchArgs           string    `protobuf:"bytes,2,opt,name=search_args,json=searchArgs,proto3" json:"search_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformSearchReq) Reset()         { *m = PlatformSearchReq{} }
func (m *PlatformSearchReq) String() string { return proto.CompactTextString(m) }
func (*PlatformSearchReq) ProtoMessage()    {}
func (*PlatformSearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{8}
}

func (m *PlatformSearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformSearchReq.Unmarshal(m, b)
}
func (m *PlatformSearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformSearchReq.Marshal(b, m, deterministic)
}
func (m *PlatformSearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformSearchReq.Merge(m, src)
}
func (m *PlatformSearchReq) XXX_Size() int {
	return xxx_messageInfo_PlatformSearchReq.Size(m)
}
func (m *PlatformSearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformSearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformSearchReq proto.InternalMessageInfo

func (m *PlatformSearchReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformSearchReq) GetSearchArgs() string {
	if m != nil {
		return m.SearchArgs
	}
	return ""
}

type PlatformSearchResp struct {
	SearchOutput         []*SearchOutput `protobuf:"bytes,1,rep,name=search_output,json=searchOutput,proto3" json:"search_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlatformSearchResp) Reset()         { *m = PlatformSearchResp{} }
func (m *PlatformSearchResp) String() string { return proto.CompactTextString(m) }
func (*PlatformSearchResp) ProtoMessage()    {}
func (*PlatformSearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{9}
}

func (m *PlatformSearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformSearchResp.Unmarshal(m, b)
}
func (m *PlatformSearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformSearchResp.Marshal(b, m, deterministic)
}
func (m *PlatformSearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformSearchResp.Merge(m, src)
}
func (m *PlatformSearchResp) XXX_Size() int {
	return xxx_messageInfo_PlatformSearchResp.Size(m)
}
func (m *PlatformSearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformSearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformSearchResp proto.InternalMessageInfo

func (m *PlatformSearchResp) GetSearchOutput() []*SearchOutput {
	if m != nil {
		return m.SearchOutput
	}
	return nil
}

type SearchOutput struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	Sentence             string   `protobuf:"bytes,5,opt,name=Sentence,proto3" json:"Sentence,omitempty"`
	Paragragh            string   `protobuf:"bytes,6,opt,name=Paragragh,proto3" json:"Paragragh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchOutput) Reset()         { *m = SearchOutput{} }
func (m *SearchOutput) String() string { return proto.CompactTextString(m) }
func (*SearchOutput) ProtoMessage()    {}
func (*SearchOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{10}
}

func (m *SearchOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOutput.Unmarshal(m, b)
}
func (m *SearchOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOutput.Marshal(b, m, deterministic)
}
func (m *SearchOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOutput.Merge(m, src)
}
func (m *SearchOutput) XXX_Size() int {
	return xxx_messageInfo_SearchOutput.Size(m)
}
func (m *SearchOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOutput proto.InternalMessageInfo

func (m *SearchOutput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SearchOutput) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SearchOutput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchOutput) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *SearchOutput) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *SearchOutput) GetParagragh() string {
	if m != nil {
		return m.Paragragh
	}
	return ""
}

type PlatformListReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	UpdatableOnly        bool      `protobuf:"varint,2,opt,name=updatable_only,json=updatableOnly,proto3" json:"updatable_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlatformListReq) Reset()         { *m = PlatformListReq{} }
func (m *PlatformListReq) String() string { return proto.CompactTextString(m) }
func (*PlatformListReq) ProtoMessage()    {}
func (*PlatformListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{11}
}

func (m *PlatformListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformListReq.Unmarshal(m, b)
}
func (m *PlatformListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformListReq.Marshal(b, m, deterministic)
}
func (m *PlatformListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformListReq.Merge(m, src)
}
func (m *PlatformListReq) XXX_Size() int {
	return xxx_messageInfo_PlatformListReq.Size(m)
}
func (m *PlatformListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformListReq proto.InternalMessageInfo

func (m *PlatformListReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *PlatformListReq) GetUpdatableOnly() bool {
	if m != nil {
		return m.UpdatableOnly
	}
	return false
}

type PlatformListResp struct {
	InstalledPlatform    []*InstalledPlatform `protobuf:"bytes,1,rep,name=installed_platform,json=installedPlatform,proto3" json:"installed_platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlatformListResp) Reset()         { *m = PlatformListResp{} }
func (m *PlatformListResp) String() string { return proto.CompactTextString(m) }
func (*PlatformListResp) ProtoMessage()    {}
func (*PlatformListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{12}
}

func (m *PlatformListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformListResp.Unmarshal(m, b)
}
func (m *PlatformListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformListResp.Marshal(b, m, deterministic)
}
func (m *PlatformListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformListResp.Merge(m, src)
}
func (m *PlatformListResp) XXX_Size() int {
	return xxx_messageInfo_PlatformListResp.Size(m)
}
func (m *PlatformListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformListResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformListResp proto.InternalMessageInfo

func (m *PlatformListResp) GetInstalledPlatform() []*InstalledPlatform {
	if m != nil {
		return m.InstalledPlatform
	}
	return nil
}

type InstalledPlatform struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Installed            string   `protobuf:"bytes,2,opt,name=Installed,proto3" json:"Installed,omitempty"`
	Latest               string   `protobuf:"bytes,3,opt,name=Latest,proto3" json:"Latest,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstalledPlatform) Reset()         { *m = InstalledPlatform{} }
func (m *InstalledPlatform) String() string { return proto.CompactTextString(m) }
func (*InstalledPlatform) ProtoMessage()    {}
func (*InstalledPlatform) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{13}
}

func (m *InstalledPlatform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstalledPlatform.Unmarshal(m, b)
}
func (m *InstalledPlatform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstalledPlatform.Marshal(b, m, deterministic)
}
func (m *InstalledPlatform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstalledPlatform.Merge(m, src)
}
func (m *InstalledPlatform) XXX_Size() int {
	return xxx_messageInfo_InstalledPlatform.Size(m)
}
func (m *InstalledPlatform) XXX_DiscardUnknown() {
	xxx_messageInfo_InstalledPlatform.DiscardUnknown(m)
}

var xxx_messageInfo_InstalledPlatform proto.InternalMessageInfo

func (m *InstalledPlatform) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *InstalledPlatform) GetInstalled() string {
	if m != nil {
		return m.Installed
	}
	return ""
}

func (m *InstalledPlatform) GetLatest() string {
	if m != nil {
		return m.Latest
	}
	return ""
}

func (m *InstalledPlatform) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PlatformInstallReq)(nil), "arduino.PlatformInstallReq")
	proto.RegisterType((*PlatformInstallResp)(nil), "arduino.PlatformInstallResp")
	proto.RegisterType((*PlatformDownloadReq)(nil), "arduino.PlatformDownloadReq")
	proto.RegisterType((*PlatformDownloadResp)(nil), "arduino.PlatformDownloadResp")
	proto.RegisterType((*PlatformUninstallReq)(nil), "arduino.PlatformUninstallReq")
	proto.RegisterType((*PlatformUninstallResp)(nil), "arduino.PlatformUninstallResp")
	proto.RegisterType((*PlatformUpgradeReq)(nil), "arduino.PlatformUpgradeReq")
	proto.RegisterType((*PlatformUpgradeResp)(nil), "arduino.PlatformUpgradeResp")
	proto.RegisterType((*PlatformSearchReq)(nil), "arduino.PlatformSearchReq")
	proto.RegisterType((*PlatformSearchResp)(nil), "arduino.PlatformSearchResp")
	proto.RegisterType((*SearchOutput)(nil), "arduino.SearchOutput")
	proto.RegisterType((*PlatformListReq)(nil), "arduino.PlatformListReq")
	proto.RegisterType((*PlatformListResp)(nil), "arduino.PlatformListResp")
	proto.RegisterType((*InstalledPlatform)(nil), "arduino.InstalledPlatform")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xd6, 0xa6, 0x21, 0x4d, 0xa6, 0xe9, 0x4f, 0x0c, 0x45, 0x4b, 0x54, 0x89, 0xc8, 0x02, 0xa9,
	0x1c, 0x9a, 0x4a, 0x20, 0x2e, 0xdc, 0x8a, 0x72, 0x89, 0x54, 0x68, 0xb4, 0xa1, 0x1c, 0x90, 0x50,
	0xe4, 0x6c, 0xcc, 0x66, 0x95, 0x5d, 0xdb, 0xd8, 0x5e, 0x50, 0xdf, 0x80, 0x33, 0x0f, 0xc0, 0x13,
	0x00, 0xcf, 0x88, 0xd6, 0x6b, 0x3b, 0x09, 0xe1, 0x80, 0x72, 0x69, 0x4f, 0xc9, 0x7c, 0xf3, 0x8d,
	0xfd, 0xf9, 0x9b, 0x19, 0x2d, 0x40, 0xcc, 0x25, 0xed, 0x0b, 0xc9, 0x35, 0x47, 0xbb, 0x44, 0xce,
	0x8a, 0x94, 0xf1, 0x6e, 0x3b, 0xe6, 0x79, 0xce, 0x59, 0x05, 0xe3, 0x9f, 0x01, 0xa0, 0x51, 0x46,
	0xf4, 0x27, 0x2e, 0xf3, 0x21, 0x53, 0x9a, 0x64, 0x59, 0x44, 0x3f, 0xa3, 0x33, 0x68, 0xa6, 0x65,
	0xc4, 0x62, 0x1a, 0x06, 0xbd, 0xe0, 0x74, 0xef, 0x79, 0xa7, 0x6f, 0x0f, 0xe8, 0x0f, 0x6d, 0x22,
	0xf2, 0x14, 0xf4, 0x0c, 0x8e, 0x84, 0x3d, 0x64, 0x22, 0x48, 0xbc, 0x20, 0x09, 0x0d, 0x6b, 0xbd,
	0xe0, 0xb4, 0x15, 0x1d, 0x3a, 0x7c, 0x54, 0xc1, 0x08, 0x43, 0x9b, 0xc8, 0x78, 0x9e, 0x6a, 0x1a,
	0xeb, 0x42, 0xd2, 0x70, 0xc7, 0xd0, 0xd6, 0x30, 0x14, 0xc2, 0xee, 0x17, 0x2a, 0x55, 0xca, 0x59,
	0x58, 0x37, 0x69, 0x17, 0xe2, 0x6f, 0x01, 0xdc, 0xdf, 0x90, 0xab, 0x04, 0x7a, 0x09, 0x4d, 0x21,
	0x79, 0x22, 0xa9, 0x52, 0x56, 0xef, 0x23, 0xaf, 0x77, 0xc0, 0xbf, 0xb2, 0x8c, 0x93, 0xd9, 0xc8,
	0x12, 0x22, 0x4f, 0x45, 0xaf, 0x60, 0x5f, 0x13, 0xb5, 0x98, 0xf8, 0xda, 0x9a, 0xa9, 0x3d, 0xf6,
	0xb5, 0xef, 0x88, 0x5a, 0xf8, 0xba, 0xb6, 0x5e, 0x89, 0xf0, 0xaf, 0x15, 0x29, 0xee, 0x8a, 0xbb,
	0x6c, 0xdd, 0x1b, 0x78, 0xb0, 0x29, 0x77, 0x6b, 0xeb, 0xf0, 0xef, 0x60, 0x79, 0xde, 0x35, 0x4b,
	0xef, 0xfe, 0xe8, 0x8c, 0xe1, 0xf8, 0x1f, 0x7a, 0x95, 0xd8, 0x1c, 0x82, 0xe0, 0xff, 0x87, 0xe0,
	0xfb, 0xca, 0xfa, 0x5c, 0x8b, 0x44, 0x92, 0x19, 0xbd, 0x75, 0x0f, 0xd6, 0x96, 0xc4, 0x8b, 0xba,
	0x9d, 0x25, 0x89, 0xa1, 0xe3, 0x94, 0x8c, 0x69, 0x29, 0x72, 0x0b, 0x77, 0x1e, 0xc3, 0x9e, 0x32,
	0xb5, 0x13, 0x22, 0x13, 0x65, 0x8d, 0x81, 0x0a, 0xba, 0x90, 0x89, 0xc2, 0xa3, 0x65, 0x0f, 0xdc,
	0x25, 0x55, 0x5b, 0x6d, 0x19, 0x2f, 0xb4, 0x28, 0x74, 0x18, 0xf4, 0x76, 0xd6, 0x64, 0x57, 0xdc,
	0x2b, 0x93, 0x8c, 0xda, 0x6a, 0x25, 0xc2, 0x3f, 0x02, 0x68, 0xaf, 0xa6, 0xd1, 0x01, 0xd4, 0x86,
	0x03, 0x23, 0xb6, 0x15, 0xd5, 0x86, 0x83, 0x72, 0xcc, 0xde, 0xdb, 0x31, 0xab, 0xf4, 0xb8, 0x10,
	0x21, 0xa8, 0xbf, 0x25, 0xb9, 0x6b, 0x8c, 0xf9, 0x8f, 0x1e, 0x42, 0xe3, 0xa2, 0xd0, 0x73, 0x2e,
	0xed, 0x4c, 0xda, 0x08, 0x75, 0xa1, 0x39, 0xa6, 0x4c, 0xd3, 0xd2, 0x88, 0x7b, 0x26, 0xe3, 0x63,
	0x74, 0x02, 0xad, 0x11, 0x91, 0x24, 0x91, 0x24, 0x99, 0x87, 0x0d, 0x93, 0x5c, 0x02, 0x38, 0x81,
	0x43, 0xf7, 0xe4, 0xcb, 0x54, 0xe9, 0x2d, 0x5c, 0x7d, 0x0a, 0x07, 0x85, 0x98, 0x11, 0x4d, 0xa6,
	0x19, 0x9d, 0x70, 0x96, 0xdd, 0x98, 0x87, 0x34, 0xa3, 0x7d, 0x8f, 0x5e, 0xb1, 0xec, 0x06, 0x7f,
	0x84, 0xa3, 0xf5, 0x8b, 0x94, 0x40, 0x43, 0x40, 0x76, 0x7f, 0xe8, 0x6c, 0xe2, 0x06, 0xd4, 0xda,
	0xdb, 0x5d, 0xbf, 0xb3, 0xa4, 0xb8, 0xfa, 0xa8, 0x93, 0xfe, 0x0d, 0xe1, 0x1c, 0x3a, 0x1b, 0xbc,
	0x0d, 0xb3, 0x4f, 0xa0, 0xe5, 0x49, 0xd6, 0xee, 0x25, 0x50, 0x9a, 0x7b, 0x49, 0x34, 0x55, 0xda,
	0x5a, 0x6e, 0x23, 0xdf, 0x88, 0xfa, 0xb2, 0x11, 0xaf, 0x9f, 0x7c, 0xc0, 0x49, 0xaa, 0xe7, 0xc5,
	0xb4, 0x1f, 0xf3, 0xfc, 0xdc, 0x2a, 0x75, 0xbf, 0x67, 0x71, 0x96, 0x9e, 0x4b, 0x11, 0x4f, 0x1b,
	0xe6, 0xd3, 0xf8, 0xe2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x00, 0x7a, 0x84, 0x3f, 0x07,
	0x00, 0x00,
}
