// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LibraryDownloadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryDownloadReq) Reset()         { *m = LibraryDownloadReq{} }
func (m *LibraryDownloadReq) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadReq) ProtoMessage()    {}
func (*LibraryDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{0}
}

func (m *LibraryDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadReq.Unmarshal(m, b)
}
func (m *LibraryDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadReq.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadReq.Merge(m, src)
}
func (m *LibraryDownloadReq) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadReq.Size(m)
}
func (m *LibraryDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadReq proto.InternalMessageInfo

func (m *LibraryDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryDownloadReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryDownloadResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryDownloadResp) Reset()         { *m = LibraryDownloadResp{} }
func (m *LibraryDownloadResp) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadResp) ProtoMessage()    {}
func (*LibraryDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{1}
}

func (m *LibraryDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadResp.Unmarshal(m, b)
}
func (m *LibraryDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadResp.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadResp.Merge(m, src)
}
func (m *LibraryDownloadResp) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadResp.Size(m)
}
func (m *LibraryDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadResp proto.InternalMessageInfo

func (m *LibraryDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type LibraryInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryInstallReq) Reset()         { *m = LibraryInstallReq{} }
func (m *LibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallReq) ProtoMessage()    {}
func (*LibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{2}
}

func (m *LibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallReq.Unmarshal(m, b)
}
func (m *LibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallReq.Merge(m, src)
}
func (m *LibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallReq.Size(m)
}
func (m *LibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallReq proto.InternalMessageInfo

func (m *LibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryInstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryInstallResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryInstallResp) Reset()         { *m = LibraryInstallResp{} }
func (m *LibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallResp) ProtoMessage()    {}
func (*LibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{3}
}

func (m *LibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallResp.Unmarshal(m, b)
}
func (m *LibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallResp.Merge(m, src)
}
func (m *LibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallResp.Size(m)
}
func (m *LibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallResp proto.InternalMessageInfo

func (m *LibraryInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryInstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUninstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUninstallReq) Reset()         { *m = LibraryUninstallReq{} }
func (m *LibraryUninstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallReq) ProtoMessage()    {}
func (*LibraryUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{4}
}

func (m *LibraryUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallReq.Unmarshal(m, b)
}
func (m *LibraryUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallReq.Merge(m, src)
}
func (m *LibraryUninstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallReq.Size(m)
}
func (m *LibraryUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallReq proto.InternalMessageInfo

func (m *LibraryUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryUninstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryUninstallResp struct {
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryUninstallResp) Reset()         { *m = LibraryUninstallResp{} }
func (m *LibraryUninstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallResp) ProtoMessage()    {}
func (*LibraryUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{5}
}

func (m *LibraryUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallResp.Unmarshal(m, b)
}
func (m *LibraryUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallResp.Merge(m, src)
}
func (m *LibraryUninstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallResp.Size(m)
}
func (m *LibraryUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallResp proto.InternalMessageInfo

func (m *LibraryUninstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUpgradeAllReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUpgradeAllReq) Reset()         { *m = LibraryUpgradeAllReq{} }
func (m *LibraryUpgradeAllReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllReq) ProtoMessage()    {}
func (*LibraryUpgradeAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{6}
}

func (m *LibraryUpgradeAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllReq.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllReq.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllReq.Merge(m, src)
}
func (m *LibraryUpgradeAllReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllReq.Size(m)
}
func (m *LibraryUpgradeAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllReq proto.InternalMessageInfo

func (m *LibraryUpgradeAllReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type LibraryUpgradeAllResp struct {
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskProgress         *TaskProgress     `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryUpgradeAllResp) Reset()         { *m = LibraryUpgradeAllResp{} }
func (m *LibraryUpgradeAllResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllResp) ProtoMessage()    {}
func (*LibraryUpgradeAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{7}
}

func (m *LibraryUpgradeAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllResp.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllResp.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllResp.Merge(m, src)
}
func (m *LibraryUpgradeAllResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllResp.Size(m)
}
func (m *LibraryUpgradeAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllResp proto.InternalMessageInfo

func (m *LibraryUpgradeAllResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryUpgradeAllResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibrarySearchReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Names                bool      `protobuf:"varint,2,opt,name=names,proto3" json:"names,omitempty"`
	Query                string    `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibrarySearchReq) Reset()         { *m = LibrarySearchReq{} }
func (m *LibrarySearchReq) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchReq) ProtoMessage()    {}
func (*LibrarySearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{8}
}

func (m *LibrarySearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchReq.Unmarshal(m, b)
}
func (m *LibrarySearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchReq.Marshal(b, m, deterministic)
}
func (m *LibrarySearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchReq.Merge(m, src)
}
func (m *LibrarySearchReq) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchReq.Size(m)
}
func (m *LibrarySearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchReq proto.InternalMessageInfo

func (m *LibrarySearchReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibrarySearchReq) GetNames() bool {
	if m != nil {
		return m.Names
	}
	return false
}

func (m *LibrarySearchReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type LibrarySearchResp struct {
	SearchOutput         []*SearchLibraryOutput `protobuf:"bytes,1,rep,name=search_output,json=searchOutput,proto3" json:"search_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LibrarySearchResp) Reset()         { *m = LibrarySearchResp{} }
func (m *LibrarySearchResp) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchResp) ProtoMessage()    {}
func (*LibrarySearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{9}
}

func (m *LibrarySearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchResp.Unmarshal(m, b)
}
func (m *LibrarySearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchResp.Marshal(b, m, deterministic)
}
func (m *LibrarySearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchResp.Merge(m, src)
}
func (m *LibrarySearchResp) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchResp.Size(m)
}
func (m *LibrarySearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchResp proto.InternalMessageInfo

func (m *LibrarySearchResp) GetSearchOutput() []*SearchLibraryOutput {
	if m != nil {
		return m.SearchOutput
	}
	return nil
}

type SearchLibraryOutput struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Releases             map[string]*LibraryRelease `protobuf:"bytes,2,rep,name=Releases,proto3" json:"Releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Latest               *LibraryRelease            `protobuf:"bytes,3,opt,name=latest,proto3" json:"latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SearchLibraryOutput) Reset()         { *m = SearchLibraryOutput{} }
func (m *SearchLibraryOutput) String() string { return proto.CompactTextString(m) }
func (*SearchLibraryOutput) ProtoMessage()    {}
func (*SearchLibraryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{10}
}

func (m *SearchLibraryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLibraryOutput.Unmarshal(m, b)
}
func (m *SearchLibraryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLibraryOutput.Marshal(b, m, deterministic)
}
func (m *SearchLibraryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLibraryOutput.Merge(m, src)
}
func (m *SearchLibraryOutput) XXX_Size() int {
	return xxx_messageInfo_SearchLibraryOutput.Size(m)
}
func (m *SearchLibraryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLibraryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLibraryOutput proto.InternalMessageInfo

func (m *SearchLibraryOutput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchLibraryOutput) GetReleases() map[string]*LibraryRelease {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *SearchLibraryOutput) GetLatest() *LibraryRelease {
	if m != nil {
		return m.Latest
	}
	return nil
}

type LibraryListReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryListReq) Reset()         { *m = LibraryListReq{} }
func (m *LibraryListReq) String() string { return proto.CompactTextString(m) }
func (*LibraryListReq) ProtoMessage()    {}
func (*LibraryListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{11}
}

func (m *LibraryListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListReq.Unmarshal(m, b)
}
func (m *LibraryListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListReq.Marshal(b, m, deterministic)
}
func (m *LibraryListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListReq.Merge(m, src)
}
func (m *LibraryListReq) XXX_Size() int {
	return xxx_messageInfo_LibraryListReq.Size(m)
}
func (m *LibraryListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListReq proto.InternalMessageInfo

func (m *LibraryListReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type LibraryListResp struct {
	Libraries            []*InstalledLibrary `protobuf:"bytes,1,rep,name=libraries,proto3" json:"libraries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LibraryListResp) Reset()         { *m = LibraryListResp{} }
func (m *LibraryListResp) String() string { return proto.CompactTextString(m) }
func (*LibraryListResp) ProtoMessage()    {}
func (*LibraryListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{12}
}

func (m *LibraryListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListResp.Unmarshal(m, b)
}
func (m *LibraryListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListResp.Marshal(b, m, deterministic)
}
func (m *LibraryListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListResp.Merge(m, src)
}
func (m *LibraryListResp) XXX_Size() int {
	return xxx_messageInfo_LibraryListResp.Size(m)
}
func (m *LibraryListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListResp proto.InternalMessageInfo

func (m *LibraryListResp) GetLibraries() []*InstalledLibrary {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type InstalledLibrary struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Installed            *LibraryRelease `protobuf:"bytes,2,opt,name=installed,proto3" json:"installed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InstalledLibrary) Reset()         { *m = InstalledLibrary{} }
func (m *InstalledLibrary) String() string { return proto.CompactTextString(m) }
func (*InstalledLibrary) ProtoMessage()    {}
func (*InstalledLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{13}
}

func (m *InstalledLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstalledLibrary.Unmarshal(m, b)
}
func (m *InstalledLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstalledLibrary.Marshal(b, m, deterministic)
}
func (m *InstalledLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstalledLibrary.Merge(m, src)
}
func (m *InstalledLibrary) XXX_Size() int {
	return xxx_messageInfo_InstalledLibrary.Size(m)
}
func (m *InstalledLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_InstalledLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_InstalledLibrary proto.InternalMessageInfo

func (m *InstalledLibrary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstalledLibrary) GetInstalled() *LibraryRelease {
	if m != nil {
		return m.Installed
	}
	return nil
}

type LibraryRelease struct {
	Author               string            `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Maintainer           string            `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Sentence             string            `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`
	Paragraph            string            `protobuf:"bytes,5,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	Website              string            `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Category             string            `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Architectures        []string          `protobuf:"bytes,8,rep,name=architectures,proto3" json:"architectures,omitempty"`
	Types                []string          `protobuf:"bytes,9,rep,name=types,proto3" json:"types,omitempty"`
	Resources            *DownloadResource `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryRelease) Reset()         { *m = LibraryRelease{} }
func (m *LibraryRelease) String() string { return proto.CompactTextString(m) }
func (*LibraryRelease) ProtoMessage()    {}
func (*LibraryRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{14}
}

func (m *LibraryRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryRelease.Unmarshal(m, b)
}
func (m *LibraryRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryRelease.Marshal(b, m, deterministic)
}
func (m *LibraryRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryRelease.Merge(m, src)
}
func (m *LibraryRelease) XXX_Size() int {
	return xxx_messageInfo_LibraryRelease.Size(m)
}
func (m *LibraryRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryRelease.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryRelease proto.InternalMessageInfo

func (m *LibraryRelease) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *LibraryRelease) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LibraryRelease) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *LibraryRelease) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *LibraryRelease) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *LibraryRelease) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *LibraryRelease) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *LibraryRelease) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *LibraryRelease) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *LibraryRelease) GetResources() *DownloadResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type DownloadResource struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Archivefilename      string   `protobuf:"bytes,2,opt,name=archivefilename,proto3" json:"archivefilename,omitempty"`
	Checksum             string   `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Cachepath            string   `protobuf:"bytes,5,opt,name=cachepath,proto3" json:"cachepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResource) Reset()         { *m = DownloadResource{} }
func (m *DownloadResource) String() string { return proto.CompactTextString(m) }
func (*DownloadResource) ProtoMessage()    {}
func (*DownloadResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3a4bf272509e0b, []int{15}
}

func (m *DownloadResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResource.Unmarshal(m, b)
}
func (m *DownloadResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResource.Marshal(b, m, deterministic)
}
func (m *DownloadResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResource.Merge(m, src)
}
func (m *DownloadResource) XXX_Size() int {
	return xxx_messageInfo_DownloadResource.Size(m)
}
func (m *DownloadResource) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResource.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResource proto.InternalMessageInfo

func (m *DownloadResource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadResource) GetArchivefilename() string {
	if m != nil {
		return m.Archivefilename
	}
	return ""
}

func (m *DownloadResource) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *DownloadResource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DownloadResource) GetCachepath() string {
	if m != nil {
		return m.Cachepath
	}
	return ""
}

func init() {
	proto.RegisterType((*LibraryDownloadReq)(nil), "arduino.LibraryDownloadReq")
	proto.RegisterType((*LibraryDownloadResp)(nil), "arduino.LibraryDownloadResp")
	proto.RegisterType((*LibraryInstallReq)(nil), "arduino.LibraryInstallReq")
	proto.RegisterType((*LibraryInstallResp)(nil), "arduino.LibraryInstallResp")
	proto.RegisterType((*LibraryUninstallReq)(nil), "arduino.LibraryUninstallReq")
	proto.RegisterType((*LibraryUninstallResp)(nil), "arduino.LibraryUninstallResp")
	proto.RegisterType((*LibraryUpgradeAllReq)(nil), "arduino.LibraryUpgradeAllReq")
	proto.RegisterType((*LibraryUpgradeAllResp)(nil), "arduino.LibraryUpgradeAllResp")
	proto.RegisterType((*LibrarySearchReq)(nil), "arduino.LibrarySearchReq")
	proto.RegisterType((*LibrarySearchResp)(nil), "arduino.LibrarySearchResp")
	proto.RegisterType((*SearchLibraryOutput)(nil), "arduino.SearchLibraryOutput")
	proto.RegisterMapType((map[string]*LibraryRelease)(nil), "arduino.SearchLibraryOutput.ReleasesEntry")
	proto.RegisterType((*LibraryListReq)(nil), "arduino.LibraryListReq")
	proto.RegisterType((*LibraryListResp)(nil), "arduino.LibraryListResp")
	proto.RegisterType((*InstalledLibrary)(nil), "arduino.InstalledLibrary")
	proto.RegisterType((*LibraryRelease)(nil), "arduino.LibraryRelease")
	proto.RegisterType((*DownloadResource)(nil), "arduino.DownloadResource")
}

func init() { proto.RegisterFile("lib.proto", fileDescriptor_bd3a4bf272509e0b) }

var fileDescriptor_bd3a4bf272509e0b = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x6b, 0x13, 0x4d,
	0x14, 0x66, 0x93, 0x36, 0x4d, 0x4e, 0x9b, 0xb7, 0xe9, 0xb4, 0x7d, 0xdf, 0x6d, 0x29, 0x2f, 0x61,
	0xe9, 0x45, 0x10, 0x9a, 0x42, 0xa5, 0x28, 0xbd, 0x91, 0x8a, 0x15, 0x94, 0xa2, 0xb2, 0x56, 0x2f,
	0x04, 0x29, 0x93, 0xcd, 0x31, 0x19, 0xb2, 0x1f, 0xd3, 0x99, 0xd9, 0x96, 0xf8, 0x07, 0x04, 0x7f,
	0x83, 0xff, 0xc7, 0xbf, 0xe4, 0xa5, 0xcc, 0xec, 0xec, 0x24, 0xe9, 0x87, 0x4a, 0x40, 0xbd, 0xda,
	0x39, 0xe7, 0x3c, 0xe7, 0x3c, 0xe7, 0x6b, 0x86, 0x85, 0x46, 0xcc, 0x7a, 0x5d, 0x2e, 0x32, 0x95,
	0x91, 0x25, 0x2a, 0xfa, 0x39, 0x4b, 0xb3, 0xed, 0x95, 0x28, 0x4b, 0x92, 0x2c, 0x2d, 0xd4, 0xc1,
	0x05, 0x90, 0x53, 0xd6, 0x13, 0x54, 0x8c, 0x9f, 0x64, 0x57, 0x69, 0x9c, 0xd1, 0x7e, 0x88, 0x17,
	0x64, 0x0f, 0xea, 0x2c, 0x95, 0x8a, 0xa6, 0x11, 0xfa, 0x5e, 0xdb, 0xeb, 0x2c, 0x1f, 0xac, 0x75,
	0xad, 0x7f, 0xf7, 0x99, 0x35, 0x84, 0x0e, 0x42, 0x08, 0x2c, 0xa4, 0x34, 0x41, 0xbf, 0xd2, 0xf6,
	0x3a, 0x8d, 0xd0, 0x9c, 0x89, 0x0f, 0x4b, 0x97, 0x28, 0x24, 0xcb, 0x52, 0xbf, 0x6a, 0xd4, 0xa5,
	0x18, 0x9c, 0xc2, 0xfa, 0x0d, 0x4a, 0xc9, 0xc9, 0x21, 0xd4, 0xb9, 0xc8, 0x06, 0x02, 0xa5, 0xb4,
	0x9c, 0x5b, 0x8e, 0xb3, 0x04, 0xbe, 0xb2, 0x80, 0xd0, 0x41, 0x03, 0x0e, 0x6b, 0x36, 0x9a, 0x49,
	0x2c, 0x8e, 0x7f, 0x7b, 0xfe, 0x9f, 0x3c, 0xd7, 0x33, 0x47, 0x39, 0x77, 0xfe, 0xe4, 0x08, 0x9a,
	0x8a, 0xca, 0xd1, 0xb9, 0xf3, 0xad, 0x18, 0xdf, 0x4d, 0xe7, 0x7b, 0x46, 0xe5, 0xc8, 0xf9, 0xad,
	0xa8, 0x29, 0x29, 0x10, 0xae, 0x93, 0x6f, 0x52, 0xf6, 0x87, 0xaa, 0x0f, 0x61, 0xe3, 0x26, 0xa7,
	0xe4, 0x37, 0xeb, 0xf0, 0x7e, 0xbd, 0x8e, 0x93, 0x49, 0x4c, 0x3e, 0x10, 0xb4, 0x8f, 0xc7, 0xf3,
	0x14, 0x12, 0x7c, 0xf6, 0x60, 0xf3, 0x96, 0x38, 0x7f, 0x67, 0x36, 0x09, 0xb4, 0x6c, 0x2e, 0xaf,
	0x91, 0x8a, 0x68, 0x38, 0xc7, 0x60, 0x36, 0x60, 0x51, 0x0f, 0xa3, 0xa0, 0xad, 0x87, 0x85, 0xa0,
	0xb5, 0x17, 0x39, 0x8a, 0xb1, 0x1d, 0x4c, 0x21, 0x04, 0x6f, 0xdd, 0x35, 0x28, 0xe9, 0x24, 0x27,
	0xc7, 0xd0, 0x94, 0x46, 0x3a, 0xcf, 0x72, 0xc5, 0x73, 0xe5, 0x7b, 0xed, 0x6a, 0x67, 0xf9, 0x60,
	0xc7, 0x91, 0x16, 0x58, 0xeb, 0xf8, 0xd2, 0x60, 0xc2, 0x95, 0xc2, 0xa5, 0x90, 0x82, 0x6f, 0x1e,
	0xac, 0xdf, 0x82, 0xd2, 0x4b, 0xf3, 0x42, 0x2f, 0x8d, 0x57, 0x2c, 0x8d, 0x3e, 0x93, 0xa7, 0x50,
	0x0f, 0x31, 0x46, 0x2a, 0x4d, 0xca, 0x9a, 0xe9, 0xde, 0x8f, 0x98, 0xba, 0x25, 0xf8, 0x24, 0x55,
	0x62, 0x1c, 0x3a, 0x5f, 0xb2, 0x0f, 0xb5, 0x98, 0x2a, 0x94, 0xca, 0x94, 0xb8, 0x7c, 0xf0, 0x9f,
	0x8b, 0x62, 0xfd, 0x2d, 0x32, 0xb4, 0xb0, 0xed, 0x33, 0x68, 0xce, 0xc4, 0x22, 0x2d, 0xa8, 0x8e,
	0x70, 0x6c, 0x93, 0xd3, 0x47, 0xb2, 0x07, 0x8b, 0x97, 0x34, 0xce, 0xd1, 0x8e, 0xf0, 0xce, 0x90,
	0x05, 0xea, 0xa8, 0xf2, 0xd0, 0x0b, 0x1e, 0xc1, 0x3f, 0xd6, 0x78, 0xca, 0xa4, 0x9a, 0x63, 0x1f,
	0x9f, 0xc3, 0xea, 0x4c, 0x00, 0xc9, 0xc9, 0x03, 0xf3, 0x24, 0x0b, 0x2a, 0x18, 0x4a, 0x3b, 0x8d,
	0xad, 0xd9, 0x10, 0x71, 0x8c, 0xfd, 0x32, 0xa7, 0x09, 0x36, 0x78, 0x0f, 0xad, 0xeb, 0x66, 0x77,
	0x71, 0xbd, 0xa9, 0x8b, 0x7b, 0x08, 0x0d, 0x56, 0xe2, 0x7e, 0x56, 0xeb, 0x04, 0x19, 0x7c, 0xad,
	0xb8, 0x62, 0xad, 0x95, 0xfc, 0x0b, 0x35, 0x9a, 0xab, 0x61, 0x26, 0x6c, 0x7c, 0x2b, 0x4d, 0x3f,
	0x0d, 0x95, 0x99, 0xa7, 0x81, 0xfc, 0x0f, 0x90, 0x50, 0x96, 0x2a, 0xca, 0x52, 0x14, 0x76, 0x3d,
	0xa7, 0x34, 0x64, 0x1b, 0xea, 0x12, 0x53, 0x85, 0xba, 0x7d, 0x0b, 0xc6, 0xea, 0x64, 0xb2, 0x03,
	0x0d, 0x4e, 0x05, 0x1d, 0x08, 0xca, 0x87, 0xfe, 0xa2, 0x31, 0x4e, 0x14, 0x9a, 0xf3, 0x0a, 0x7b,
	0x92, 0x29, 0xf4, 0x6b, 0x05, 0xa7, 0x15, 0x75, 0xcc, 0x88, 0x2a, 0x1c, 0x64, 0x62, 0xec, 0x2f,
	0x15, 0x31, 0x4b, 0x99, 0xec, 0x42, 0x53, 0x2f, 0x1d, 0x53, 0x18, 0xa9, 0x5c, 0xa0, 0xf4, 0xeb,
	0xed, 0x6a, 0xa7, 0x11, 0xce, 0x2a, 0xf5, 0x7d, 0x52, 0x63, 0x8e, 0xd2, 0x6f, 0x18, 0x6b, 0x21,
	0xe8, 0x41, 0x09, 0x94, 0x59, 0x2e, 0x22, 0x94, 0x3e, 0xdc, 0xf1, 0x64, 0x84, 0x16, 0x11, 0x4e,
	0xb0, 0xc1, 0x17, 0x0f, 0x5a, 0xd7, 0xed, 0x7a, 0x1f, 0x73, 0x11, 0x97, 0xfb, 0x98, 0x8b, 0x98,
	0x74, 0x60, 0xd5, 0xa4, 0x71, 0x89, 0x1f, 0x58, 0x8c, 0x53, 0xef, 0xef, 0x75, 0xb5, 0xa9, 0x70,
	0x88, 0xd1, 0x48, 0xe6, 0x89, 0xed, 0xa9, 0x93, 0xf5, 0x06, 0x48, 0xf6, 0xb1, 0xe8, 0x66, 0x35,
	0x34, 0x67, 0xdd, 0xc9, 0x88, 0x46, 0x43, 0xe4, 0x54, 0xb9, 0x4e, 0x3a, 0xc5, 0xe3, 0xdd, 0x77,
	0xc1, 0x80, 0xa9, 0x61, 0xde, 0xeb, 0x46, 0x59, 0xb2, 0x6f, 0x0b, 0x2a, 0xbf, 0x7b, 0x51, 0xcc,
	0xf6, 0x05, 0x8f, 0x7a, 0x35, 0xf3, 0x73, 0x70, 0xff, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2,
	0xe2, 0xe7, 0x42, 0x40, 0x08, 0x00, 0x00,
}
