// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upload.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Fqbn                 string    `protobuf:"bytes,2,opt,name=fqbn,proto3" json:"fqbn,omitempty"`
	SketchPath           string    `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath,proto3" json:"sketch_path,omitempty"`
	Port                 string    `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Verbose              bool      `protobuf:"varint,5,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Verify               bool      `protobuf:"varint,6,opt,name=verify,proto3" json:"verify,omitempty"`
	ImportFile           string    `protobuf:"bytes,7,opt,name=import_file,json=importFile,proto3" json:"import_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UploadReq) Reset()         { *m = UploadReq{} }
func (m *UploadReq) String() string { return proto.CompactTextString(m) }
func (*UploadReq) ProtoMessage()    {}
func (*UploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

func (m *UploadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReq.Unmarshal(m, b)
}
func (m *UploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReq.Marshal(b, m, deterministic)
}
func (m *UploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReq.Merge(m, src)
}
func (m *UploadReq) XXX_Size() int {
	return xxx_messageInfo_UploadReq.Size(m)
}
func (m *UploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReq proto.InternalMessageInfo

func (m *UploadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *UploadReq) GetFqbn() string {
	if m != nil {
		return m.Fqbn
	}
	return ""
}

func (m *UploadReq) GetSketchPath() string {
	if m != nil {
		return m.SketchPath
	}
	return ""
}

func (m *UploadReq) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *UploadReq) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *UploadReq) GetVerify() bool {
	if m != nil {
		return m.Verify
	}
	return false
}

func (m *UploadReq) GetImportFile() string {
	if m != nil {
		return m.ImportFile
	}
	return ""
}

type UploadResp struct {
	OutStream            []byte   `protobuf:"bytes,1,opt,name=out_stream,json=outStream,proto3" json:"out_stream,omitempty"`
	ErrStream            []byte   `protobuf:"bytes,2,opt,name=err_stream,json=errStream,proto3" json:"err_stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResp) Reset()         { *m = UploadResp{} }
func (m *UploadResp) String() string { return proto.CompactTextString(m) }
func (*UploadResp) ProtoMessage()    {}
func (*UploadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1}
}

func (m *UploadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResp.Unmarshal(m, b)
}
func (m *UploadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResp.Marshal(b, m, deterministic)
}
func (m *UploadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResp.Merge(m, src)
}
func (m *UploadResp) XXX_Size() int {
	return xxx_messageInfo_UploadResp.Size(m)
}
func (m *UploadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResp proto.InternalMessageInfo

func (m *UploadResp) GetOutStream() []byte {
	if m != nil {
		return m.OutStream
	}
	return nil
}

func (m *UploadResp) GetErrStream() []byte {
	if m != nil {
		return m.ErrStream
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadReq)(nil), "arduino.UploadReq")
	proto.RegisterType((*UploadResp)(nil), "arduino.UploadResp")
}

func init() { proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5) }

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x43, 0xad, 0xa5, 0x4c, 0xb9, 0xb8, 0x07, 0xb3, 0x31, 0x31, 0x12, 0xe2, 0x81, 0x4b,
	0x69, 0xa2, 0x6f, 0xe0, 0xc1, 0x44, 0x4f, 0x06, 0xe3, 0xc5, 0x0b, 0x59, 0xb6, 0x8b, 0x6c, 0x04,
	0x66, 0x3b, 0x2c, 0x4d, 0x7c, 0x51, 0x9f, 0xc7, 0xb0, 0x0b, 0x9e, 0x66, 0xe6, 0xff, 0xe6, 0xcf,
	0x64, 0x7e, 0x88, 0x47, 0xd3, 0xa2, 0x38, 0xe6, 0x86, 0xd0, 0x22, 0x0b, 0x05, 0x1d, 0x47, 0xdd,
	0xe3, 0x4d, 0x2c, 0xb1, 0xeb, 0xb0, 0xf7, 0x72, 0xfa, 0x1b, 0x40, 0xf4, 0xe1, 0xf6, 0x0a, 0x75,
	0x62, 0x7b, 0xd8, 0xea, 0x7e, 0xb0, 0xa2, 0x97, 0x8a, 0x07, 0x49, 0x90, 0xed, 0x1e, 0xae, 0xf2,
	0xd9, 0x97, 0xbf, 0xcc, 0xa0, 0xf8, 0x5f, 0x61, 0x0c, 0xd6, 0xf5, 0xa9, 0xea, 0xf9, 0x2a, 0x09,
	0xb2, 0xa8, 0x70, 0x3d, 0xbb, 0x83, 0xdd, 0xf0, 0xad, 0xac, 0x6c, 0x4a, 0x23, 0x6c, 0xc3, 0x2f,
	0x1c, 0x02, 0x2f, 0xbd, 0x09, 0xdb, 0x4c, 0x26, 0x83, 0x64, 0xf9, 0xda, 0x9b, 0xa6, 0x9e, 0x71,
	0x08, 0xcf, 0x8a, 0x2a, 0x1c, 0x14, 0xbf, 0x4c, 0x82, 0x6c, 0x5b, 0x2c, 0x23, 0xbb, 0x86, 0xcd,
	0x59, 0x91, 0xae, 0x7f, 0xf8, 0xc6, 0x81, 0x79, 0x9a, 0xce, 0xe8, 0x6e, 0xf2, 0x96, 0xb5, 0x6e,
	0x15, 0x0f, 0xfd, 0x19, 0x2f, 0x3d, 0xeb, 0x56, 0xa5, 0xaf, 0x00, 0xcb, 0x5f, 0x83, 0x61, 0xb7,
	0x00, 0x38, 0xda, 0x72, 0xb0, 0xa4, 0x44, 0xe7, 0x5e, 0x8b, 0x8b, 0x08, 0x47, 0xfb, 0xee, 0x84,
	0x09, 0x2b, 0xa2, 0x05, 0xaf, 0x3c, 0x56, 0x44, 0x1e, 0x3f, 0xdd, 0x7f, 0xa6, 0x5f, 0xda, 0x36,
	0x63, 0x95, 0x4b, 0xec, 0x0e, 0x73, 0x20, 0x4b, 0xdd, 0xcb, 0x56, 0x1f, 0xc8, 0xc8, 0x6a, 0xe3,
	0x12, 0x7d, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x73, 0xf6, 0xe5, 0x78, 0x01, 0x00, 0x00,
}
